name: Docker Image CI - Generate PDF using asciidoctor-pdf

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor 
    steps:
    - name: Get current date
      id: date
      run: |
        echo "NOW=$(date +'%d.%m.%Y')" >> $GITHUB_ENV
        echo "VERSION=1.1.$(($GITHUB_RUN_NUMBER+5))" >> $GITHUB_ENV

    - uses: actions/checkout@v2
      
    - name: Run asciidoctor-pdf
      run: asciidoctor-pdf -r asciidoctor-mathematical -a compress -a mathematical-format=svg -a revdate=$NOW -a revnumber=$VERSION src/asciidoc/*.adoc
    
    - name: Archive generated pdf's
      uses: actions/upload-artifact@v2
      with:
        name: generated-pravidla-pdf.zip
        path: src/asciidoc/*.pdf
      
       
